# Generated by Django 2.1.15 on 2020-02-16 17:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID único para el idioma del libro', primary_key=True, serialize=False)),
                ('language', models.CharField(help_text='Idioma del libro', max_length=10, verbose_name='Idioma')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='languagebook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.LanguageBook'),
        ),
    ]
