# Generated by Django 2.1.15 on 2020-02-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200216_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagebook',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
